name: Clone integration

on:
  push:
    branches:
      - master

jobs:
  clone-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone integration
        run: python integration-clone.py my-integration new-integration
