name: export integration
on:
  push:
    branches:
      - master

jobs:
  export-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code including your Python script

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'  # Replace with the desired Python version

      - name: Run Python script
        run: python oic-cd.py ${{ secrets.OIC_USERNAME }} ${{ secrets.OIC_PASSWORD }} ${{ secrets.OIC_URL }} ${{ secrets.APP_VAR }} ${{ secrets.APP_VAR_VERSION }}
