name: export integration
on:
  workflow_dispatch:
    inputs:
      oic-username:
        description: 'Oracle Integration Cloud Username'
        required: true
      oic-password:
        description: 'Oracle Integration Cloud Password'
        required: true
      oic-url:
        description: 'Oracle Integration Cloud URL'
        required: true
      app-var:
        description: 'APP_VAR value'
        required: true
      app-var-version:
        description: 'APP_VAR version'
        required: true  
jobs:
  export-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code including your Python script

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'  # Replace with the desired Python version

      - name: Run Python script
        run: python oic-cd.py ${{ inputs.oic-username }} ${{ inputs.oic-password }} ${{ inputs.oic-url }} ${{ inputs.app-var }} ${{ inputs.app-var-version }}

      