name: Export and Import Integration

on:
  workflow_dispatch:
    inputs:
      oic-username:
        description: 'Oracle Integration Cloud Username'
        required: true
      oic-password:
        description: 'Oracle Integration Cloud Password'
        required: true
      oic-url:
        description: 'Oracle Integration Cloud URL'
        required: true
      app-var:
        description: 'APP_VAR value'
        required: true

jobs:
  export-integration:
    runs-on: ubuntu-latest
    
    outputs:
      exported_file: ${{ steps.export.outputs.exported_file }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code including your Python script

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'  # Replace with the desired Python version

      - name: Run Python script
        run: python oic-cd.py ${{ inputs.oic-username }} ${{ inputs.oic-password }} ${{ inputs.oic-url }} ${{ inputs.app-var }}
      - name: Debug Environment Variables
        run: |
          echo "OIC_USERNAME: ${{ secrets.OIC_USERNAME }}"
          echo "OIC_URL: ${{ secrets.OIC_URL }}"
          echo "APP_VAR: ${{ secrets.APP_VAR }}"
          
      - name: Export Integration Step
        run: |
          echo "This is an Export Integration step"
          export_file_path="${GITHUB_WORKSPACE}/myfile_01.iar"
          if curl -vvv -u ${{ inputs.oic-username }}:${{ inputs.oic-password }} -o "${export_file_path}" ${{ inputs.oic-url }}/ic/api/integration/v1/integrations/${{ inputs.app-var }}/archive; then
            echo "Exported successfully! File exported to: ${export_file_path}"
          else
            echo "Export failed."
            exit 1
          fi    

  import-integration:
    needs: export-integration
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '.10.8'  # Replace with the desired Python version

      - name: Debug Environment Variables
        run: |
              echo "OIC_USERNAME: ${{ secrets.OIC_USERNAME }}"
              echo "OIC_URL: ${{ secrets.OIC_URL }}"
    
      - name: Import Integration Step
        run: |
              echo "This is an Import Integration step"
              curl -vvv -s -u ${{ secrets.OIC_USERNAME }}:${{ secrets.OIC_PASSWORD }} -H "Accept: application/json" -X PUT -F "file=@${{ needs.export-integration.outputs.exported_file }};type=application/octet-stream" ${{ secrets.OIC_URL }}/ic/api/integration/v1/integrations/archive