name: export integration

on:
  workflow_dispatch:
    inputs:
      oic-username:
        description: 'Oracle Integration Cloud Username'
        required: true
      oic-password:
        description: 'Oracle Integration Cloud Password'
        required: true
      oic-url:
        description: 'Oracle Integration Cloud URL'
        required: true
      app-var:
        description: 'APP_VAR value'
        required: true

jobs:
  clone-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'  # Replace with the desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have any Python package dependencies

      - name: Run Python script
        run: python oic-cd.py ${{ inputs.oic-username }} ${{ inputs.oic-password }} ${{ inputs.oic-url }} ${{ inputs.app-var }}
